--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JeroGamingYT-pm-pl/InventoryKeepChance
build-by-default: true
branches:
- main
projects:
  InventoryKeepChance:
    path: ""
    icon: icon.png
...
